[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/dracula.toml"]

[window]
dimensions = { columns = 80, lines = 30}
startup_mode = "Windowed"
title = "Terminal"
dynamic_title = true
decorations_theme_variant = "Dark"
decorations = "Full"
opacity = 0.8
blur = true
padding = { y = 20, x = 20 }

[scrolling]
history = 10000
multiplier = 3

[cursor]
unfocused_hollow = true
thickness = 0.15

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 18
builtin_box_drawing = true
offset.x = 3 # For letter spacing (default: 0)
